on:
  push:
    branches:
      - master

env:
  PACKAGE: config-better
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: release-please
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      did_release: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          release-type: rust
          package-name: ${{ env.PACKAGE }}
          changelog-types: '[{ "type": "feat", "section": "Features", "hidden": false },{ "type": "fix", "section": "Bug Fixes", "hidden": false },{ "type": "refactor", "section": "Code Refactoring", "hidden": false }]'
  publish-release:
    name: publish-release (config-better)
    needs: release-please
    if: ${{ needs.release-please.outputs.did_release }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Publish
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
