on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: test
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust-version: [1.63.0, stable]
        features: ["sync", "async", "async-tokio"]
        exclude:
          - rust-version: 1.63.0
            features: "sync"
          - rust-version: 1.63.0
            features: "async"
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Test
        run: cargo test --features ${{ matrix.features }}
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust-version: [1.63.0, stable]
        features: ["sync", "async", "async-tokio"]
        exclude:
          - rust-version: 1.63.0
            features: "sync"
          - rust-version: 1.63.0
            features: "async"
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Build
        run: cargo build --release --features ${{ matrix.features }}
