on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: test
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Test
        run: cargo test --locked

      - name: Publish
        run: cargo publish --dry-run --locked
